use_frameworks!

platform :ios, '10.0'

target 'QQXPhotosBrowser_Example' do
  pod 'QQXPhotosBrowser', :path => '../'

  target 'QQXPhotosBrowser_Tests' do
    inherit! :search_paths
	pod 'SDWebImage'
    pod 'FBSnapshotTestCase'
  end
end
